version: "3"
services:
 opendj:
  image: demo-opendj
  container_name: demo-opendj 
  ports:
   - "1389:1389"

 cas:
  image: demo-cas
  container_name: demo-cas
  environment:
   LDAP_HOST: demo-opendj
  depends_on:
   - opendj

 postgres:
  image: demo-postgres
  container_name: demo-postgres
  ports:
   - "5432:5432"


 es-node-1:
  image: elasticsearch:1.7.6
  command: "elasticsearch -Des.cluster.name=demo"
  container_name: demo-es-1
  ports:
   - "9200:9200"

 es-node-2:
  image: elasticsearch:1.7.6
  command: "elasticsearch -Des.cluster.name=demo"
  container_name: demo-es-2
  ports:
   - "9201:9200"

 nuxeo:
  image: demo-nuxeo
  container_name: demo-nuxeo
  environment:
   PUBLIC_HOST: ${EXTRANET_HOST}
   NUXEO_DB_HOST: demo-postgres
   LDAP_HOST: demo-opendj
   NUXEO_ES_CLUSTER: demo
   NUXEO_ES_NODES: demo-es-1:9300,demo-es-2:9300
   CAS_HOST: demo-cas:8080
   CAS_PUBLIC_HOST: ${INTRANET_HOST}
  depends_on:
   - postgres
   - opendj
   - cas
   - es-node-1
   - es-node-2

 mysql:
  image: mysql
  container_name: demo-mysql
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  environment:
   MYSQL_DATABASE: portaldb
   MYSQL_USER: portal
   MYSQL_PASSWORD: osivia
   MYSQL_ROOT_PASSWORD: osivia

 portal-1:
  image: demo-portal
  container_name: demo-portal-1
  environment:
   NUXEO_HOST: demo-nuxeo
   PORTAL_DB_HOST: demo-mysql
   CAS_HOST: demo-cas
   CAS_PUBLIC_HOST: ${INTRANET_HOST}
   LDAP_HOST: demo-opendj
   PORTAL_MEMBERS: demo-portal-2
   EXTRANET_HOST: ${EXTRANET_HOST}
   INTRANET_HOST: ${INTRANET_HOST}
#  volumes:
#   - ../share/deploy:/opt/portal/custom/deploy
  ports:
   - "8787:8787"
  depends_on:
   - mysql
   - opendj
   - cas
   - nuxeo

 portal-2:
  image: demo-portal
  container_name: demo-portal-2
  environment:
   NUXEO_HOST: demo-nuxeo
   PORTAL_DB_HOST: demo-mysql
   CAS_HOST: demo-cas
   CAS_PUBLIC_HOST: ${INTRANET_HOST}
   LDAP_HOST: demo-opendj
   PORTAL_MEMBERS: demo-portal-1
   EXTRANET_HOST: ${EXTRANET_HOST}
   INTRANET_HOST: ${INTRANET_HOST}
#  volumes:
#   - ../share/deploy:/opt/portal/custom/deploy
  ports:
   - "8788:8787"
  depends_on:
   - mysql
   - opendj
   - cas
   - nuxeo

 httpd:
  image: demo-httpd
  container_name: demo-httpd
  environment:
   NUXEO_HOST: demo-nuxeo
   CAS_HOST: demo-cas
   PORTAL_HOSTS: demo-portal-1
  ports:
   - "80:80"
   - "443:443"
  depends_on:
   - nuxeo
   - cas
   - portal-1
   - portal-2

 
