version: "3"
services:
 opendj:
  image: basic_opendj
  container_name: demo-opendj 
  ports:
   - "1389:1389"

 cas:
  image: basic_cas
  container_name: demo-cas
  environment:
   LDAP_HOST: demo-opendj
  depends_on:
   - opendj

 postgres:
  image: basic_pg95
  container_name: demo-postgres
  ports:
   - "5432:5432"


 es-node-1:
  image: elasticsearch:1.7.6
  command: "elasticsearch -Des.cluster.name=demo"
  container_name: demo-es-1
  environment:
   ES_HEAP_SIZE: 256m

 es-node-2:
  image: elasticsearch:1.7.6
  command: "elasticsearch -Des.cluster.name=demo"
  container_name: demo-es-2
  environment:
   ES_HEAP_SIZE: 256m

 nuxeo:
  image: basic_osivia_nx46
  container_name: demo-nuxeo
  environment:
   PUBLIC_HOST: ${PUBLIC_HOST}
   NUXEO_DB_HOST: demo-postgres
   LDAP_HOST: demo-opendj
   NUXEO_ES_CLUSTER: demo
   NUXEO_ES_NODES: demo-es-1:9300,demo-es-2:9300
   CAS_HOST: demo-cas:8080
  depends_on:
   - postgres
   - opendj
   - cas
   - es-node-1
   - es-node-2

 httpd:
  image: basic_http
  container_name: demo-http
  hostname: ${PUBLIC_HOST}
  environment:
   NUXEO_HOST: demo-nuxeo
   CAS_HOST: demo-cas
  ports:
   - "80:80"
   - "443:443"
  depends_on:
   - nuxeo
   - cas



