version: "3"
services:
  opendj:
    image: osivia/opendj:tribu
    ports:
      - 1389:1389
    volumes:
      - opendj-data:/opt/opendj/db
      - opendj-backup:/backup      
  cas:
    image: osivia/cas:tribu
    environment:
      - LDAP_HOST=opendj
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket      
    ports:
      - 8080
      - 8000:8000
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-backup:/backup
      - ../tools/postgres:/root/bin
  es:
    image: elasticsearch:1.7.6
    command: elasticsearch -Des.cluster.name=es-cluster
    ports:
      - 9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:4.1
    environment:
      - ELASTICSEARCH_URL=http://es:9200    
    ports:
      - 5601:5601
  fakesmtp:
    image: munkyboy/fakesmtp
    ports:
      - 25
    volumes:
      - ./mails:/var/mail
  fakesmtp-web:
    image: mjstewart/fakesmtp-web:1.2
    ports:
      - 60500:8080
    volumes:
      - ./mails:/var/mail
    environment:
      - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=10
    depends_on:
      - fakesmtp
  nuxeo-proxy:
    image: osivia/httpd-nx:tribu
    environment:
      - NUXEO_HOSTS=nuxeo1,nuxeo2
  nuxeo1:
    image: osivia/nuxeo:tribu
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - LDAP_HOST=opendj
      - CAS_HOST=cas:8080
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=es-cluster
      - NUXEO_ES_NODES=es:9300
      - OO_HOST=onlyoffice
      - MAIL_HOST=fakesmtp
      - CLUSTERID=1
    ports:
      - 8080
      - 8788:8788
    volumes:
      - nuxeo-data:/data
    depends_on:
      - postgres
      - es
  nuxeo2:
    image: osivia/nuxeo:tribu
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - LDAP_HOST=opendj
      - CAS_HOST=cas:8080
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=es-cluster
      - NUXEO_ES_NODES=es:9300
      - OO_HOST=onlyoffice
      - MAIL_HOST=fakesmtp
      - CLUSTERID=2
    ports:
      - 8080
      - 8789:8788
    volumes:
      - nuxeo-data:/data
    depends_on:
      - postgres
      - es
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=portaldb
      - MYSQL_USER=portal
      - MYSQL_PASSWORD=osivia
      - MYSQL_ROOT_PASSWORD=osivia
    volumes:
      - mysql-data:/var/lib/mysql
  portal:
    image: osivia/portal:tribu
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - NUXEO_HOST=nuxeo-proxy
      - NUXEO_PORT=80
      - PORTAL_DB_HOST=mysql
      - CAS_HOST=cas
      - LDAP_HOST=opendj
      - MAIL_HOST=fakesmtp
    ports:
      - 8080
      - 8787:8787
    depends_on:
      - mysql
  httpd:
    image: osivia/httpd:tribu
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - CAS_HOST=cas
      - NUXEO_HOST=nuxeo-proxy
      - NUXEO_PORT=80
      - PORTAL_HOSTS=portal
      - OO_HOST=onlyoffice
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./certs:/etc/ssl/certs       
  onlyoffice:
    image: onlyoffice/documentserver
    volumes:
      - ./onlyoffice_local.json:/etc/onlyoffice/documentserver/local.json      
volumes:
  opendj-data:
  opendj-backup:
  postgres-data:
  postgres-backup:
  es-data:
  nuxeo-data:
  mysql-data:

