version: "3"
services:
  opendj:
    image: osivia/opendj:tribu
    build: ../opendj
    ports:
      - 1389:1389
    volumes:
      - opendj-data:/opt/opendj/db
      - opendj-backup:/backup      
  cas:
    image: osivia/cas:tribu
    build: ../cas
    environment:
      - CAS_TOMCAT_PORT=${CAS_PORT}
      - CAS_TOMCAT_ADMIN_PORT=8011
      - CAS_TOMCAT_AJP_PORT=0
      - LDAP_HOST=opendj
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    ports:
      - 8083:8080
      - 8000:8000
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-backup:/backup
      - ../tools/postgres:/root/bin
  es:
#    image: elasticsearch:1.7.6
    build: ../es
    command: elasticsearch -Des.cluster.name=es-cluster -Des.path.repo=//usr/share/elasticsearch/
    ports:
      - 9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:4.1
    profiles:
      - kibana
    environment:
      - ELASTICSEARCH_URL=http://es:9200    
    ports:
      - 5601:5601
  fakesmtp:
    image: munkyboy/fakesmtp
    ports:
      - 25
    volumes:
      - ./mails:/var/mail
  nuxeo:
    image: osivia/nuxeo:tribu
    build: ../nuxeo
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - NUXEO_TOMCAT_PORT=${NUXEO_PORT}
      - NUXEO_TOMCAT_ADMIN_PORT=8010
      - NUXEO_TOMCAT_AJP_PORT=0
      - LDAP_HOST=opendj
      - CAS_HOST=cas
      - CAS_PORT=${CAS_PORT}
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=es-cluster
      - NUXEO_ES_NODES=es:9300
      - OO_HOST=onlyoffice
      - MAIL_HOST=fakesmtp      
    ports:
      - 8383:8080
      - 8788:8788
    volumes:
      - nuxeo-data:/data
    depends_on:
      - postgres
      - es
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=portaldb
      - MYSQL_USER=portal
      - MYSQL_PASSWORD=osivia
      - MYSQL_ROOT_PASSWORD=osivia
    volumes:
      - mysql-data:/var/lib/mysql
  portal:
    image: osivia/portal:tribu
    build: ../portal
    profiles:
      - portal
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - PORTAL_JBOSS_PORT=${PORTAL_PORT}
      - NUXEO_HOST=nuxeo
      - NUXEO_PORT=${NUXEO_PORT}
      - PORTAL_DB_HOST=mysql
      - CAS_HOST=cas
      - CAS_PORT=${CAS_PORT}
      - LDAP_HOST=opendj
      - MAIL_HOST=fakesmtp
    ports:
      - 8080
      - 8787:8787
    depends_on:
      - mysql
  httpd:
    image: osivia/httpd:tribu
    build: ../httpd
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - CAS_HOST=cas
      - CAS_PORT=${CAS_PORT}
      - NUXEO_HOST=nuxeo
      - NUXEO_PORT=${NUXEO_PORT}
      - PORTAL_HOSTS=portal,portal2
      - PORTAL_PORT=${PORTAL_PORT}
      - OO_HOST=onlyoffice
      - PORTALV2_HOST=portalv2
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./certs:/etc/ssl/certs
    extra_hosts:
      - dev.local:host-gateway
  onlyoffice:
    image: osivia/onlyoffice:tribu
    build: ../onlyoffice
    profiles:
      - onlyoffice
  api:
    image: osivia/tribu-api:tribu
    build: ../api
    profiles:
      - api
    ports:
      - 8181:8080
      - 8790:8000
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket        
  portalv2:
    image: belharra/portalv2:tribu
    build: ../portalv2
    profiles:
      - portalv2
    ports:
      - 8282:8080
      - 8791:8000
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
  collabora:
    #image: collabora/code
    build: ../collabora
    cap_add:
      - MKNOD
    privileged: true
    environment:
      - aliasgroup1=https://tribu.local:443
      #- "extra_params=--o:ssl.enable=false --o:per_document.always_save_on_exit=true"
    ports:
      - "9980:9980"
    extra_hosts:
      - tribu.local:host-gateway
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  opendj-data:
  opendj-backup:
  postgres-data:
  postgres-backup:
  es-data:
  nuxeo-data:
  mysql-data:

