version: "3"
services:
  opendj:
    image: osivia/opendj:toutatice
    ports:
      - 1389:${PUBLIC_LDAP_PORT}
    volumes:
      - opendj-data:/opt/opendj/db
  cas:
    image: osivia/cas:toutatice
    environment:
      - LDAP_HOST=opendj
    ports:
      - 8080
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  es:
    image: elasticsearch:1.7.6
    command: elasticsearch -Des.cluster.name=es-cluster
    ports:
      - 9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  nuxeo:
    image: osivia/nuxeo:toutatice-syndication
    build: ../nuxeo/
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - LDAP_HOST=opendj
      - CAS_HOST=cas:8080
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=es-cluster
      - NUXEO_ES_NODES=es:9300
    ports:
      - 8080
      - 8788:${PUBLIC_NUXEO_DEBUG_PORT}
    volumes:
      - nuxeo-data:/data
    depends_on:
      - postgres
      - es
  content-store:
    image: toutatice/content-store:toutatice
    build: ../content-store
    ports:
      - 8080
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=portaldb
      - MYSQL_USER=portal
      - MYSQL_PASSWORD=osivia
      - MYSQL_ROOT_PASSWORD=osivia
    volumes:
      - mysql-data:/var/lib/mysql
  portal:
    image: osivia/portal:toutatice-syndication
    build: ../portal/
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - NUXEO_HOST=nuxeo
      - PORTAL_DB_HOST=mysql
      - CAS_HOST=cas
      - LDAP_HOST=opendj
    ports:
      - 8080
      - 8787:${PUBLIC_PORTAL_DEBUG_PORT}
    depends_on:
      - mysql
  httpd:
    image: osivia/httpd:toutatice-syndication
    build: ../httpd/
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - HTTPS_PROVIDED=${HTTPS_PROVIDED}
      - CAS_HOST=cas
      - NUXEO_HOST=nuxeo
      - PORTAL_HOSTS=portal
    networks:
      default:
        aliases:
          - ${PUBLIC_HOST}
    ports:
      - 80:${PUBLIC_HTTP_PORT}
      - 443:${PUBLIC_HTTPS_PORT}
    volumes:
      - httpd-ssl:/etc/ssl
  kibana:
    image: kibana:4.1
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - 5601:${PUBLIC_KIBANA_PORT}
networks:
  default:
volumes:
  opendj-data:
  postgres-data:
  es-data:
  nuxeo-data:
  mysql-data:
  httpd-ssl:
