version: "3"
services:
  opendj:
    image: osivia/opendj:toutatice-mutualisation
    build: ../opendj
    ports:
      - 1389:${PUBLIC_LDAP_PORT}
    volumes:
      - opendj-data:/opt/opendj/db
  cas:
    image: osivia/cas:toutatice-mutualisation
    build: ../cas
    environment:
      - LDAP_HOST=opendj
    ports:
      - 8080
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres-notif:
    image: postgres:9.5
    profiles:
      - notifications
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=notif
      - POSTGRES_DB=notifdb
    volumes:
      - postgres-notif-data:/var/lib/postgresql/data
  es:
    image: elasticsearch:1.7.6
    command: elasticsearch -Des.cluster.name=es-cluster
    ports:
      - 9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  fakesmtp:
    image: munkyboy/fakesmtp
    profiles:
      - fakesmtp
    ports:
      - 25
    volumes:
      - ./mails:/var/mail
#  fakesmtp-web:
#    image: mjstewart/fakesmtp-web:1.2
#    ports:
#      - 60500:8080
#    volumes:
#      - ./mails:/var/mail
#    environment:
#      - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=10
#    depends_on:
#      - fakesmtp
  nuxeo:
    image: osivia/nuxeo:toutatice-mutualisation
    build: ../nuxeo
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - LDAP_HOST=opendj
      - CAS_HOST=cas:8080
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=es-cluster
      - NUXEO_ES_NODES=es:9300
      - OO_HOST=onlyoffice
      - MAIL_HOST=fakesmtp
    ports:
      - 8080
      - 8788:${PUBLIC_NUXEO_DEBUG_PORT}
    volumes:
      - nuxeo-data:/data
    depends_on:
      - postgres
#      - postgres-notif
      - es
  portal:
    image: osivia/portal:toutatice-mutualisation
    build: ../portal
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - NUXEO_HOST=nuxeo
      - CAS_HOST=cas
      - LDAP_HOST=opendj
      - MAIL_HOST=fakesmtp
    ports:
      - 8080
      - 8787:${PUBLIC_PORTAL_DEBUG_PORT}
    volumes:
      - portal-data-h5p:/opt/h5p      
  httpd:
    image: osivia/httpd:toutatice-mutualisation
    build: ../httpd
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - HTTPS_PROVIDED=${HTTPS_PROVIDED}
      - CAS_HOST=cas
      - NUXEO_HOST=nuxeo
      - PORTAL_HOSTS=portal
      - OO_HOST=onlyoffice
      - WEBMAIL_HOST=fakesmtp-web
    ports:
      - 80:${PUBLIC_HTTP_PORT}
      - 443:${PUBLIC_HTTPS_PORT}
    volumes:
      - httpd-ssl:/etc/ssl
  onlyoffice:
    profiles:
      - onlyoffice
    image: osivia/onlyoffice:toutatice-mutualisation
    build: ../onlyoffice
#  onlyoffice:
#    image: onlyoffice/documentserver:5.5
#    volumes:
#      - ./onlyoffice_local.json:/etc/onlyoffice/documentserver/local.json
  kibana:
    image: kibana:4.1
    profiles:
      - kibana
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - 5601:${PUBLIC_KIBANA_PORT}
#  contentstore:
#    image: osivia/contentstore:toutatice
#    ports:
#      - 8080:8080
#      - 8789:8000
#    environment:
#      - JPDA_ADDRESS=8000
#      - JPDA_TRANSPORT=dt_socket
volumes:
  opendj-data:
  postgres-data:
  postgres-notif-data:
  es-data:
  nuxeo-data:
  mail-data:
  httpd-ssl:
  portal-data-h5p:
