version: "3"
services:
  opendj:
    image: osivia/opendj:elen
    build: ../opendj
    ports:
      - 1389:${PUBLIC_LDAP_PORT}
    volumes:
      - opendj-data:/opt/opendj/db
  cas:
    image: osivia/cas:elen
    build: ../cas
    environment:
      - LDAP_HOST=opendj
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8789:5005"
      - 8080
      - 8443
    links:
      - opendj
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  es:
    image: elasticsearch:1.7.6
    command: elasticsearch -Des.cluster.name=es-cluster
    ports:
      - 9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  nuxeo:
    image: osivia/nuxeo:elen
    build: ../nuxeo
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - LDAP_HOST=opendj
      - CAS_HOST=cas:8080
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=es-cluster
      - NUXEO_ES_NODES=es:9300
    ports:
      - 8181:8080
      - 8788:${PUBLIC_NUXEO_DEBUG_PORT}
    volumes:
      - nuxeo-data:/data
    depends_on:
      - postgres
      - es
  portal:
    image: osivia/portal:elen
    build: ../../elen-portail/docker/portal-bundle
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - NUXEO_HOST=nuxeo
      - CAS_HOST=cas
      - LDAP_HOST=opendj
    ports:
      - 8080
      - 8787:${PUBLIC_PORTAL_DEBUG_PORT}
    extra_hosts:
      - "api-binaires:host-gateway"
      - "api-actualites:host-gateway"
      - "safran-hub:host-gateway"
  httpd:
    image: osivia/httpd:elen
    build: ../httpd
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - HTTPS_PROVIDED=${HTTPS_PROVIDED}
      - CAS_HOST=cas
      - NUXEO_HOST=nuxeo
      - PORTAL_HOSTS=portal
    ports:
      - 80:${PUBLIC_HTTP_PORT}
      - 443:${PUBLIC_HTTPS_PORT}
    volumes:
      - httpd-ssl:/etc/ssl
  kibana:
    image: kibana:4.1
    profiles:
      - kibana
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - 5601:${PUBLIC_KIBANA_PORT}
  apis:
    image: roquio/apis:elen
    build: ../apis
    ports:
      - 8282:8080
      - 8790:8000
    environment:
      - LDAP_HOST=opendj
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
volumes:
  opendj-data:
  postgres-data:
  es-data:
  nuxeo-data:
  httpd-ssl:
