version: "3"
services:
    opendj:
        image: osivia/opendj:cloud-ens
        ports:
            - 1389:1389
        volumes:
            - opendj-data:/opt/opendj/db
    tomcat:
        image: osivia/tomcat:cloud-ens
        environment:
            - LDAP_HOST=opendj
            - JPDA_ADDRESS=8000
            - JPDA_TRANSPORT=dt_socket
            - PUBLIC_HOST=${PUBLIC_HOST}
            - PRONOTE_SERVICEVALIDATE_URL=${PRONOTE_SERVICEVALIDATE_URL}
        ports:
            - 8080
            - 8789:8000
        volumes:
            - httpd-ssl:/export/httpd/ssl
        depends_on:
           - httpd    
    postgres:
        image: postgres:9.5
        environment:
            - POSTGRES_PASSWORD=osivia
            - POSTGRES_USER=nuxeo
            - POSTGRES_DB=nuxeodb
        volumes:
            - postgres-data:/var/lib/postgresql/data
    es:
        image: elasticsearch:1.7.6
        command: elasticsearch -Des.cluster.name=cloud-ens-cluster
        volumes:
            - es-data:/usr/share/elasticsearch/data
    kibana:
        image: kibana:4.1
        environment:
            - ELASTICSEARCH_URL=http://es:9200
        ports:
            - 5601:5601
    fakesmtp:
        image: munkyboy/fakesmtp
        ports:
            - 25
        volumes:
            - ./mails:/var/mail
    fakesmtp-web:
        image: mjstewart/fakesmtp-web:1.2
        ports:
            - 60500:8080
        volumes:
            - ./mails:/var/mail
        environment:
            - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=10
        depends_on:
           - fakesmtp               
    nuxeo:
        image: osivia/nuxeo:cloud-ens
        environment:
            - PUBLIC_HOST=${PUBLIC_HOST}
            - LDAP_HOST=opendj
            - CAS_HOST=tomcat:8080
            - NUXEO_DB_HOST=postgres
            - NUXEO_ES_CLUSTER=cloud-ens-cluster
            - NUXEO_ES_NODES=es:9300
            - OO_HOST=onlyoffice
        ports:
            - 8080
            - 8788:8788
        volumes:
            - nuxeo-data:/data
        depends_on:
            - postgres
            - es
    mysql:
        image: mysql:5.7
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - MYSQL_DATABASE=portaldb
            - MYSQL_USER=portal
            - MYSQL_PASSWORD=osivia
            - MYSQL_ROOT_PASSWORD=osivia
        volumes:
            - mysql-data:/var/lib/mysql
    portal-1:
        image: osivia/portal:cloud-ens
        environment:
            - PUBLIC_HOST=${PUBLIC_HOST}
            - NUXEO_HOST=nuxeo
            - PORTAL_DB_HOST=mysql
            - CAS_HOST=tomcat
            - LDAP_HOST=opendj
            - PRONOTE_OAUTH2_CLIENT_SECRET=${PRONOTE_OAUTH2_CLIENT_SECRET}
            - PRONOTE_JWT_SECRET=${PRONOTE_JWT_SECRET}
            - PRONOTE_JWT_PUBLIC_KEY_PATH=${PRONOTE_JWT_PUBLIC_KEY_PATH}
            - PRONOTE_ETB_SERVICE_URL_GET=${PRONOTE_ETB_SERVICE_URL_GET}
            - PRONOTE_ETB_SERVICE_URL_CHECK=${PRONOTE_ETB_SERVICE_URL_CHECK}
#           - MAIL_HOST=fakesmtp           
        ports:
            - 8080
            - 8787:8787
        volumes:
            - ${PRONOTE_HOST_RESOURCES_PATH}:/var/resources            
        depends_on:
            - mysql
    httpd:
        image: osivia/httpd:cloud-ens
        environment:
            - PUBLIC_HOST=${PUBLIC_HOST}
            - CAS_HOST=tomcat
            - NUXEO_HOST=nuxeo
            - PORTAL_HOSTS=portal-1
            - OO_HOST=onlyoffice
            - WEBMAIL_HOST=fakesmtp-web
            - PUBLIC_HOST_HTTPS_CRT=${PUBLIC_HOST_HTTPS_CRT}
            - PUBLIC_HOST_HTTPS_KEY=${PUBLIC_HOST_HTTPS_KEY}            
        ports:
            - 80:80
            - 81:81            
            - 443:443
        volumes:
            - ${PRONOTE_HOST_RESOURCES_PATH}:/var/resources                    
            - httpd-ssl:/etc/ssl
        networks:
            default:
                aliases:
                    - ${PUBLIC_HOST}
    onlyoffice:
        image: onlyoffice/documentserver
        volumes:
            - ./onlyoffice_local.json:/etc/onlyoffice/documentserver/local.json
volumes:
    opendj-data:
    postgres-data:
    es-data:
    nuxeo-data:
    mysql-data:
    httpd-ssl: