version: "3"
services:
  opendj:
    image: opendj:tribu
    ports:
      - 1389:1389
  cas:
    image: cas:tribu
    environment:
      - LDAP_HOST=opendj
    ports:
      - 8080
    depends_on:
      - opendj
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  es:
    image: elasticsearch:1.7.6
    command: elasticsearch -Des.cluster.name=es-cluster
    ports:
      - 9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  nuxeo:
    image: nuxeo:tribu
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - LDAP_HOST=opendj
      - CAS_HOST=cas:8080
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=es-cluster
      - NUXEO_ES_NODES=es:9300
      - OO_HOST=onlyoffice
    ports:
      - 8080
      - 8788
    volumes:
      - nuxeo-data:/data
    depends_on:
      - opendj
      - cas
      - postgres
      - es
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=portaldb
      - MYSQL_USER=portal
      - MYSQL_PASSWORD=osivia
      - MYSQL_ROOT_PASSWORD=osivia
    volumes:
      - mysql-data:/var/lib/mysql
  portal:
    image: portal:tribu
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - NUXEO_HOST=nuxeo
      - PORTAL_DB_HOST=mysql
      - CAS_HOST=cas
      - LDAP_HOST=opendj
    ports:
      - 8080
      - 8787:8787
    depends_on:
      - mysql
      - opendj
      - cas
      - nuxeo
  httpd:
    image: httpd:tribu
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - CAS_HOST=cas
      - NUXEO_HOST=nuxeo
      - PORTAL_HOSTS=portal
      - OO_HOST=onlyoffice
    ports:
    - 80:80
    - 443:443
    depends_on:
    - cas
    - nuxeo
    - portal
    - onlyoffice
    volumes:
      - ./certs:/etc/ssl/certs       
  onlyoffice:
    image: onlyoffice/documentserver
    volumes:
      - ./onlyoffice_local.json:/etc/onlyoffice/documentserver/local.json      
volumes:
  postgres-data:
  es-data:
  nuxeo-data:
  mysql-data:

