version: "3"
services:
  opendj:
    image: roquio/opendj:greta
    build: ../opendj
    ports:
      - 1389:1389
    volumes:
      - opendj-data:/opt/opendj/db
  cas:
    image: roquio/cas:greta
    build: ../cas
    environment:
      - LDAP_HOST=opendj
    ports:
      - 8080
  postgres:
    image: roquio/postgres
    build: ../postgres
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  es:
    image: elasticsearch:1.7.6
    command: elasticsearch -Des.cluster.name=es-cluster
    ports:
      - 9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  fakesmtp:
    image: munkyboy/fakesmtp
    profiles:
      - fakesmtp
    ports:
      - 25
    volumes:
      - ./mails:/var/mail
  nuxeo:
    image: roquio/nuxeo:greta
    build: ../nuxeo
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - LDAP_HOST=opendj
      - CAS_HOST=cas:8080
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=es-cluster
      - NUXEO_ES_NODES=es:9300
      - MAIL_HOST=fakesmtp
    ports:
      - 8080
      - 8788:8788
    volumes:
      - nuxeo-data:/data
    depends_on:
      - postgres
      - es
  mysql:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=portaldb
      - MYSQL_USER=portal
      - MYSQL_PASSWORD=osivia
      - MYSQL_ROOT_PASSWORD=osivia
    volumes:
      - mysql8-data:/var/lib/mysql
  portal:
    image: roquio/portal:greta
    build: ../portal
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - NUXEO_HOST=nuxeo
      - PORTAL_DB_HOST=mysql
      - CAS_HOST=cas
      - LDAP_HOST=opendj
      - MAIL_HOST=fakesmtp
    ports:
      - 8080
      - 8787:8787
    depends_on:
      - mysql
  httpd:
    image: roquio/httpd:greta
    build: ../httpd
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - CAS_HOST=cas
      - NUXEO_HOST=nuxeo
      - PORTAL_HOSTS=portal
    ports:
      - 80:80
      - 443:443
    volumes:
      - httpd-ssl:/etc/ssl
  kibana:
    image: kibana:4.1
    profiles:
      - kibana
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - 5601:5601
volumes:
  opendj-data:
  postgres-data:
  es-data:
  nuxeo-data:
  mysql8-data:
  mail-data:
  httpd-ssl:
