version: "3"
services:    
    demo-cas:
      environment:
        - LDAP_HOST=demo-opendj
      image: 'osivia/cas:latest'
      depends_on:
        - demo-opendj
    demo-es-master:
      command: elasticsearch -Des.cluster.name=demo -Dnetwork.host=0.0.0.0 -Ddiscovery.zen.minimum_master_nodes=1 -Ddiscovery.zen.ping.unicast.hosts=demo-es-master
      image: 'elasticsearch:1.7.6'
      ports:
        - '9200:9200'
    demo-httpd:
      environment:
        - CAS_HOST=demo-cas
        - NUXEO_HOST=demo-nuxeo
        - 'PORTAL_HOSTS=demo-portal-1'
        - OO_HOST=onlyoffice        
      image: 'osivia/httpd:certif'
      depends_on:
        - demo-cas
        - demo-nuxeo
        - demo-portal-1
        - onlyoffice
      ports:
        - '80:80'
        - '443:443'
    demo-mysql:
      command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
      environment:
        - MYSQL_DATABASE=portaldb
        - MYSQL_PASSWORD=osivia
        - MYSQL_ROOT_PASSWORD=osivia
        - MYSQL_USER=portal
      image: 'mysql:5.7'
    demo-nuxeo:
      environment:
        - 'CAS_HOST=demo-cas:8080'
        - CAS_PUBLIC_HOST=dev-intra.osivia.org
        - LDAP_HOST=demo-opendj
        - NUXEO_DB_HOST=demo-postgres
        - NUXEO_ES_CLUSTER=demo
        - 'NUXEO_ES_NODES=demo-es-master:9300'
        - PUBLIC_HOST=dev-public.osivia.org
        - OO_HOST=onlyoffice-ip        
      image: 'osivia/nuxeo:dev'
      depends_on:
        - demo-cas
        - demo-es-master
        - demo-opendj
        - demo-postgres
      ports:
        - "8788:8788"
    demo-opendj:
      image: 'osivia/opendj:latest'
    demo-portal-1:
      environment:
        - CAS_HOST=demo-cas
        - CAS_PUBLIC_HOST=dev-intra.osivia.org
        - EXTRANET_HOST=dev-public.osivia.org
        - INTRANET_HOST=dev-intra.osivia.org
        - LDAP_HOST=demo-opendj
        - NUXEO_HOST=demo-nuxeo
        - PORTAL_DB_HOST=demo-mysql
      image: 'osivia/portal:dev'
      ports:
        - "8787:8787"
      volumes:
        - .\distrib\demo-distribution-prod-4.7-SNAPSHOT:/opt/demo-distribution-prod-4.7-SNAPSHOT
      depends_on:
        - demo-cas
        - demo-mysql
        - demo-nuxeo
        - demo-opendj
    demo-postgres:
      image: 'osivia/postgres:latest'
    onlyoffice:
      image: onlyoffice/documentserver
      volumes:
        - .\onlyoffice_local.json:/etc/onlyoffice/documentserver/local.json        
      
