ALTER USER postgres WITH PASSWORD 'osivia';

CREATE ROLE nuxeo LOGIN PASSWORD 'osivia' NOINHERIT VALID UNTIL 'infinity';
CREATE DATABASE nuxeodb WITH ENCODING='UTF8' OWNER=nuxeo;

CREATE ROLE pad LOGIN PASSWORD 'osivia' NOINHERIT VALID UNTIL 'infinity';
CREATE DATABASE paddb WITH ENCODING='UTF8' OWNER=pad;
